const SB_URL = 'https://afetbwtnyheysfezrgns.supabase.co';
const SB_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZXRid3RueWhleXNmZXpyZ25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NTExNTUsImV4cCI6MjA5MjMyNzE1NX0.yGary4tOciBQl4AGWVNKVKaBt4rQI7BH7ZZrwDlZHIo';
const SB_HEADERS = {
  'Content-Type':  'application/json',
  'apikey':        SB_KEY,
  'Authorization': `Bearer ${SB_KEY}`,
};

function esc(s){
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
}

const MYMEMORY_LANG = {
  en:'en-US',
  ja:'ja-JP', ko:'ko-KR', zh:'zh-CN', ar:'ar-SA', hi:'hi-IN', th:'th-TH',
  vi:'vi-VN', id:'id-ID', ms:'ms-MY',
  es:'es-ES', pt:'pt-BR', fr:'fr-FR', de:'de-DE', it:'it-IT', nl:'nl-NL',
  ru:'ru-RU', uk:'uk-UA', pl:'pl-PL', tr:'tr-TR', el:'el-GR', sv:'sv-SE',
};

// ── UI言語テキスト ──────────────────────────────
const UI_TEXT = {
  en: {
    waiting:        'Waiting',
    recording:      'Recording',
    participants:   'Participants',
    you:            '(You)',
    waitingUser:    'Waiting for others...',
    times:          'times',
    seeTranslation: 'See translation',
    close:          'Close',
    translating:    'Translating...',
    transError:     'Translation failed',
    transFail:      'Translation unavailable',
    speakHint:      'Hold the button to speak (Space key also works)',
    listening:      'Listening... speak now',
    micOff:         'Mic is OFF. Press button to turn ON',
    logTitle:       'Live Minutes',
    otherCount:     'Others',
  },
  ja: {
    waiting:        '待機中',
    recording:      '認識中',
    participants:   '参加者',
    you:            '（あなた）',
    waitingUser:    '参加待ち',
    times:          '回',
    seeTranslation: '訳を見る',
    close:          '閉じる',
    translating:    '翻訳中...',
    transError:     '翻訳に失敗しました',
    transFail:      '翻訳できませんでした',
    speakHint:      'ボタンを押している間、声を認識します（Spaceキーでも）',
    listening:      '話してください...',
    micOff:         'マイクがOFFです。ボタンを押してONにしてください',
    logTitle:       'リアルタイム議事録',
    otherCount:     '他の参加者',
  },
  ko: {
    waiting:        '대기 중',
    recording:      '인식 중',
    participants:   '참가자',
    you:            '（나）',
    waitingUser:    '참가 대기 중',
    times:          '회',
    seeTranslation: '번역 보기',
    close:          '닫기',
    translating:    '번역 중...',
    transError:     '번역에 실패했습니다',
    transFail:      '번역할 수 없습니다',
    speakHint:      '버튼을 누르는 동안 음성을 인식합니다',
    listening:      '말씀해 주세요...',
    micOff:         '마이크가 꺼져 있습니다. 버튼을 눌러 켜세요',
    logTitle:       '실시간 회의록',
    otherCount:     '다른 참가자',
  },
  zh: {
    waiting:        '等待中',
    recording:      '识别中',
    participants:   '参与者',
    you:            '（我）',
    waitingUser:    '等待加入',
    times:          '次',
    seeTranslation: '查看翻译',
    close:          '关闭',
    translating:    '翻译中...',
    transError:     '翻译失败',
    transFail:      '无法翻译',
    speakHint:      '按住按钮进行语音识别',
    listening:      '请说话...',
    micOff:         '麦克风已关闭，请按按钮开启',
    logTitle:       '实时会议记录',
    otherCount:     '其他参与者',
  },
  es: {
    waiting:        'En espera',
    recording:      'Grabando',
    participants:   'Participantes',
    you:            '(Tú)',
    waitingUser:    'Esperando participantes...',
    times:          'veces',
    seeTranslation: 'Ver traducción',
    close:          'Cerrar',
    translating:    'Traduciendo...',
    transError:     'Error de traducción',
    transFail:      'No se pudo traducir',
    speakHint:      'Mantén el botón para hablar',
    listening:      'Habla ahora...',
    micOff:         'Micrófono apagado. Presiona para activar',
    logTitle:       'Actas en tiempo real',
    otherCount:     'Otros participantes',
  },
  fr: {
    waiting:        'En attente',
    recording:      'Enregistrement',
    participants:   'Participants',
    you:            '(Vous)',
    waitingUser:    'En attente de participants...',
    times:          'fois',
    seeTranslation: 'Voir la traduction',
    close:          'Fermer',
    translating:    'Traduction...',
    transError:     'Échec de la traduction',
    transFail:      'Traduction indisponible',
    speakHint:      'Maintenez le bouton pour parler',
    listening:      'Parlez maintenant...',
    micOff:         'Micro éteint. Appuyez pour activer',
    logTitle:       'Procès-verbal en direct',
    otherCount:     'Autres participants',
  },
  de: {
    waiting:        'Warten',
    recording:      'Aufnahme',
    participants:   'Teilnehmer',
    you:            '(Sie)',
    waitingUser:    'Warten auf Teilnehmer...',
    times:          'Mal',
    seeTranslation: 'Übersetzung anzeigen',
    close:          'Schließen',
    translating:    'Übersetzen...',
    transError:     'Übersetzung fehlgeschlagen',
    transFail:      'Übersetzung nicht verfügbar',
    speakHint:      'Taste gedrückt halten zum Sprechen',
    listening:      'Bitte sprechen...',
    micOff:         'Mikrofon aus. Taste drücken zum Einschalten',
    logTitle:       'Echtzeit-Protokoll',
    otherCount:     'Andere Teilnehmer',
  },
  pt: {
    waiting:        'Aguardando',
    recording:      'Gravando',
    participants:   'Participantes',
    you:            '(Você)',
    waitingUser:    'Aguardando participantes...',
    times:          'vezes',
    seeTranslation: 'Ver tradução',
    close:          'Fechar',
    translating:    'Traduzindo...',
    transError:     'Falha na tradução',
    transFail:      'Não foi possível traduzir',
    speakHint:      'Segure o botão para falar',
    listening:      'Fale agora...',
    micOff:         'Microfone desligado. Pressione para ativar',
    logTitle:       'Ata em tempo real',
    otherCount:     'Outros participantes',
  },
};

// 現在の言語のUIテキストを取得（未対応言語はEnglishにフォールバック）
function t(key){
  const lang = typeof myLang !== 'undefined' ? myLang : 'en';
  const texts = UI_TEXT[lang] || UI_TEXT['en'];
  return texts[key] || UI_TEXT['en'][key] || key;
}
