const SB_URL = 'https://afetbwtnyheysfezrgns.supabase.co';
const SB_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZXRid3RueWhleXNmZXpyZ25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NTExNTUsImV4cCI6MjA5MjMyNzE1NX0.yGary4tOciBQl4AGWVNKVKaBt4rQI7BH7ZZrwDlZHIo';
const SB_HEADERS = {
  'Content-Type':  'application/json',
  'apikey':        SB_KEY,
  'Authorization': `Bearer ${SB_KEY}`,
};

function esc(s){
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
}

const MYMEMORY_LANG = {
  en:'en-US',
  ja:'ja-JP', ko:'ko-KR', zh:'zh-TW', ar:'ar-SA', hi:'hi-IN', th:'th-TH',
  vi:'vi-VN', id:'id-ID', ms:'ms-MY',
  es:'es-ES', pt:'pt-BR', fr:'fr-FR', de:'de-DE', it:'it-IT', nl:'nl-NL',
  ru:'ru-RU', uk:'uk-UA', pl:'pl-PL', tr:'tr-TR', el:'el-GR', sv:'sv-SE',
};

const UI_TEXT = {
  en: {
    // 会議画面
    waiting:        'Waiting',
    recording:      'Recording',
    participants:   'Participants',
    you:            '(You)',
    waitingUser:    'Waiting for others...',
    times:          'times',
    seeTranslation: 'See translation',
    close:          'Close',
    translating:    'Translating...',
    transError:     'Translation failed',
    transFail:      'Translation unavailable',
    speakHint:      'Hold the button to speak (Space key also works)',
    listening:      'Listening... speak now',
    micOff:         'Mic is OFF. Press button to turn ON',
    logTitle:       'Live Minutes',
    otherCount:     'Others',
    endBtn:         'End',
    langLabel:      'Translation language',
    wordBridge:     'Find words (WordBridge)',
    wordHint:       'Words will appear as you speak',
    // ダッシュボード
    dashTitle:      'Session Report',
    dashClose:      'Close',
    greatJob:       'Great job! 🎉',
    dashSub:        'Well done! Here is your record.',
    statSpeaks:     'Utterances',
    statWords:      'Total words',
    statTrans:      'Translation used',
    statWB:         'WordBridge used',
    statTime:       'Duration',
    statTopWords:   'Words you used most',
    noData:         'No data',
    // アンケート
    surveyTitle:    'Survey (approx. 3 min)',
    surveySection1: 'About today\'s conversation',
    surveySection2: 'About English & international exchange',
    surveyWTCNote:  '1 = Strongly disagree  〜  6 = Strongly agree',
    surveyFree:     'Free comments (impressions, suggestions, etc.)',
    surveyFreePH:   'Write freely here',
    surveySubmit:   'Submit',
    surveyDone:     '✅ Submitted! Thank you!',
    surveyError:    'Submission failed. Please try again.',
    qa1q: 'How satisfied were you with today\'s conversation overall?',
    qa1lo:'Unsatisfied', qa1hi:'Satisfied',
    qa2q: 'How actively were you able to speak today?',
    qa2lo:'Not at all', qa2hi:'Very actively',
    qa3q: 'Was SpeakEase easy to use?',
    qa3lo:'Difficult', qa3hi:'Easy',
    qa4q: 'Was WordBridge (word suggestions) helpful?',
    qa4lo:'Not helpful', qa4hi:'Very helpful',
    qa5q: 'Was the live minutes (transcription) helpful?',
    qa5lo:'Not helpful', qa5hi:'Very helpful',
    qa6q: 'Would you like to use this system for international exchange again?',
    qa6lo:'No', qa6hi:'Yes',
    wtc: [
      'I feel nervous about what others think when I speak English.',
      'I worry about making grammar mistakes when speaking English.',
      'I think it would be difficult to speak English for over an hour.',
      'I can start a conversation in English on my own.',
      'After a conversation, I regret that I could have spoken better.',
      'I enjoy the time I spend using English.',
      'I want to study English more in the future.',
    ],
  },
  ja: {
    waiting:        '待機中',
    recording:      '認識中',
    participants:   '参加者',
    you:            '（あなた）',
    waitingUser:    '参加待ち',
    times:          '回',
    seeTranslation: '訳を見る',
    close:          '閉じる',
    translating:    '翻訳中...',
    transError:     '翻訳に失敗しました',
    transFail:      '翻訳できませんでした',
    speakHint:      'ボタンを押している間、声を認識します（Spaceキーでも）',
    listening:      '話してください...',
    micOff:         'マイクがOFFです。ボタンを押してONにしてください',
    logTitle:       'リアルタイム議事録',
    otherCount:     '他の参加者',
    endBtn:         '終了',
    langLabel:      '訳の言語',
    wordBridge:     '単語を探す（WordBridge）',
    wordHint:       '発言が認識されると関連する単語が出てきます',
    dashTitle:      '会話分析レポート',
    dashClose:      '閉じる',
    greatJob:       'Great job! 🎉',
    dashSub:        '会話お疲れさまでした。あなたの記録です。',
    statSpeaks:     '発言回数',
    statWords:      '総単語数',
    statTrans:      '翻訳ボタンを押した回数',
    statWB:         '単語提案を使った回数',
    statTime:       '対話時間',
    statTopWords:   'よく使った単語',
    noData:         'データなし',
    surveyTitle:    'アンケート（所要時間：約3分）',
    surveySection1: '今回の会話について',
    surveySection2: '英語・国際交流への意欲について（6件法）',
    surveyWTCNote:  '1=全く当てはまらない　〜　6=非常によく当てはまる',
    surveyFree:     '自由記述（感想・改善点など）',
    surveyFreePH:   '自由にご記入ください',
    surveySubmit:   '回答を送信する',
    surveyDone:     '✅ 送信しました！ありがとうございました。',
    surveyError:    '送信に失敗しました。もう一度お試しください。',
    qa1q: '今日の会話全体の満足度はどのくらいでしたか？',
    qa1lo:'不満', qa1hi:'満足',
    qa2q: '今日の会話でどのくらい積極的に発言できましたか？',
    qa2lo:'できなかった', qa2hi:'できた',
    qa3q: 'SpeakEaseのツールは使いやすかったですか？',
    qa3lo:'使いにくい', qa3hi:'使いやすい',
    qa4q: '単語提案（WordBridge）は役に立ちましたか？',
    qa4lo:'役立たない', qa4hi:'役立った',
    qa5q: 'リアルタイム議事録は役に立ちましたか？',
    qa5lo:'役立たない', qa5hi:'役立った',
    qa6q: 'またこのシステムを使って国際交流をしたいと思いますか？',
    qa6lo:'思わない', qa6hi:'思う',
    wtc: [
      '英語を話すとき、他人の評価が気になる',
      '英語を話すとき、文法が間違っているのではないかと不安になる',
      '1時間以上英語で話し続けることは難しいと思う',
      '英語を話すとき、自分から会話を始めることができる',
      '会話が終わった後、もっとうまく話せたのにと後悔する',
      '英語を使っている時間は楽しい',
      '今後もっと英語を勉強したいと思う',
    ],
  },
  ko: {
    waiting:        '대기 중',
    recording:      '인식 중',
    participants:   '참가자',
    you:            '（나）',
    waitingUser:    '참가 대기 중',
    times:          '회',
    seeTranslation: '번역 보기',
    close:          '닫기',
    translating:    '번역 중...',
    transError:     '번역에 실패했습니다',
    transFail:      '번역할 수 없습니다',
    speakHint:      '버튼을 누르는 동안 음성을 인식합니다',
    listening:      '말씀해 주세요...',
    micOff:         '마이크가 꺼져 있습니다. 버튼을 눌러 켜세요',
    logTitle:       '실시간 회의록',
    otherCount:     '다른 참가자',
    endBtn:         '종료',
    langLabel:      '번역 언어',
    wordBridge:     '단어 찾기（WordBridge）',
    wordHint:       '발언이 인식되면 관련 단어가 나타납니다',
    dashTitle:      '대화 분석 리포트',
    dashClose:      '닫기',
    greatJob:       'Great job! 🎉',
    dashSub:        '수고하셨습니다! 당신의 기록입니다.',
    statSpeaks:     '발언 횟수',
    statWords:      '총 단어 수',
    statTrans:      '번역 버튼 사용 횟수',
    statWB:         '단어 제안 사용 횟수',
    statTime:       '대화 시간',
    statTopWords:   '자주 사용한 단어',
    noData:         '데이터 없음',
    surveyTitle:    '설문조사（약 3분）',
    surveySection1: '오늘 대화에 대해',
    surveySection2: '영어 및 국제 교류 의욕에 대해（6점 척도）',
    surveyWTCNote:  '1=전혀 그렇지 않다　〜　6=매우 그렇다',
    surveyFree:     '자유 서술（감상・개선점 등）',
    surveyFreePH:   '자유롭게 작성해 주세요',
    surveySubmit:   '제출하기',
    surveyDone:     '✅ 제출되었습니다! 감사합니다.',
    surveyError:    '제출에 실패했습니다. 다시 시도해 주세요.',
    qa1q: '오늘 대화 전체의 만족도는 어느 정도였나요？',
    qa1lo:'불만족', qa1hi:'만족',
    qa2q: '오늘 대화에서 얼마나 적극적으로 발언했나요？',
    qa2lo:'전혀 못함', qa2hi:'매우 적극적',
    qa3q: 'SpeakEase는 사용하기 편했나요？',
    qa3lo:'불편함', qa3hi:'편리함',
    qa4q: '단어 제안（WordBridge）이 도움이 되었나요？',
    qa4lo:'도움 안됨', qa4hi:'매우 도움됨',
    qa5q: '실시간 회의록이 도움이 되었나요？',
    qa5lo:'도움 안됨', qa5hi:'매우 도움됨',
    qa6q: '이 시스템으로 다시 국제 교류를 하고 싶나요？',
    qa6lo:'아니오', qa6hi:'예',
    wtc: [
      '영어를 말할 때 다른 사람의 평가가 신경 쓰인다',
      '영어를 말할 때 문법이 틀릴까봐 불안하다',
      '1시간 이상 영어로 말하는 것은 어렵다고 생각한다',
      '영어로 말할 때 스스로 대화를 시작할 수 있다',
      '대화가 끝난 후 더 잘 말할 수 있었는데 하고 후회한다',
      '영어를 사용하는 시간이 즐겁다',
      '앞으로 영어를 더 공부하고 싶다',
    ],
  },
  zh: {
    waiting:        '等待中',
    recording:      '识别中',
    participants:   '参与者',
    you:            '（我）',
    waitingUser:    '等待加入',
    times:          '次',
    seeTranslation: '查看翻译',
    close:          '关闭',
    translating:    '翻译中...',
    transError:     '翻译失败',
    transFail:      '无法翻译',
    speakHint:      '按住按钮进行语音识别',
    listening:      '请说话...',
    micOff:         '麦克风已关闭，请按按钮开启',
    logTitle:       '实时会议记录',
    otherCount:     '其他参与者',
    endBtn:         '结束',
    langLabel:      '翻译语言',
    wordBridge:     '查找单词（WordBridge）',
    wordHint:       '发言被识别后会出现相关单词',
    dashTitle:      '对话分析报告',
    dashClose:      '关闭',
    greatJob:       'Great job! 🎉',
    dashSub:        '辛苦了！这是您的记录。',
    statSpeaks:     '发言次数',
    statWords:      '总单词数',
    statTrans:      '翻译按钮使用次数',
    statWB:         '单词建议使用次数',
    statTime:       '对话时间',
    statTopWords:   '常用单词',
    noData:         '暂无数据',
    surveyTitle:    '问卷调查（约3分钟）',
    surveySection1: '关于今天的对话',
    surveySection2: '关于英语和国际交流的意愿（6分制）',
    surveyWTCNote:  '1=完全不符合　〜　6=非常符合',
    surveyFree:     '自由填写（感想・改善建议等）',
    surveyFreePH:   '请自由填写',
    surveySubmit:   '提交回答',
    surveyDone:     '✅ 提交成功！谢谢您！',
    surveyError:    '提交失败，请再试一次。',
    qa1q: '您对今天对话的整体满意度如何？',
    qa1lo:'不满意', qa1hi:'满意',
    qa2q: '今天的对话中您能积极发言到什么程度？',
    qa2lo:'完全没有', qa2hi:'非常积极',
    qa3q: 'SpeakEase使用起来方便吗？',
    qa3lo:'不方便', qa3hi:'很方便',
    qa4q: '单词建议（WordBridge）有帮助吗？',
    qa4lo:'没帮助', qa4hi:'很有帮助',
    qa5q: '实时会议记录有帮助吗？',
    qa5lo:'没帮助', qa5hi:'很有帮助',
    qa6q: '您想再次使用这个系统进行国际交流吗？',
    qa6lo:'不想', qa6hi:'想',
    wtc: [
      '说英语时，我在意别人的评价',
      '说英语时，我担心语法错误',
      '我认为用英语说话超过1小时很困难',
      '说英语时，我能主动开始对话',
      '对话结束后，我后悔没有说得更好',
      '使用英语的时间很愉快',
      '我想今后更努力学习英语',
    ],
  },
  es: {
    waiting:        'En espera',
    recording:      'Grabando',
    participants:   'Participantes',
    you:            '(Tú)',
    waitingUser:    'Esperando participantes...',
    times:          'veces',
    seeTranslation: 'Ver traducción',
    close:          'Cerrar',
    translating:    'Traduciendo...',
    transError:     'Error de traducción',
    transFail:      'No se pudo traducir',
    speakHint:      'Mantén el botón para hablar',
    listening:      'Habla ahora...',
    micOff:         'Micrófono apagado. Presiona para activar',
    logTitle:       'Actas en tiempo real',
    otherCount:     'Otros participantes',
    endBtn:         'Terminar',
    langLabel:      'Idioma de traducción',
    wordBridge:     'Buscar palabras（WordBridge）',
    wordHint:       'Las palabras aparecerán cuando hables',
    dashTitle:      'Informe de la conversación',
    dashClose:      'Cerrar',
    greatJob:       'Great job! 🎉',
    dashSub:        '¡Buen trabajo! Aquí está tu registro.',
    statSpeaks:     'Intervenciones',
    statWords:      'Palabras totales',
    statTrans:      'Traducciones usadas',
    statWB:         'WordBridge usado',
    statTime:       'Duración',
    statTopWords:   'Palabras más usadas',
    noData:         'Sin datos',
    surveyTitle:    'Encuesta（aprox. 3 min）',
    surveySection1: 'Sobre la conversación de hoy',
    surveySection2: 'Sobre tu motivación para el inglés（escala de 6）',
    surveyWTCNote:  '1=Totalmente en desacuerdo　〜　6=Totalmente de acuerdo',
    surveyFree:     'Comentarios libres',
    surveyFreePH:   'Escribe libremente aquí',
    surveySubmit:   'Enviar respuestas',
    surveyDone:     '✅ ¡Enviado! Gracias.',
    surveyError:    'Error al enviar. Por favor, inténtalo de nuevo.',
    qa1q: '¿Cuál fue tu satisfacción general con la conversación de hoy?',
    qa1lo:'Insatisfecho', qa1hi:'Satisfecho',
    qa2q: '¿Cuánto pudiste participar activamente hoy?',
    qa2lo:'Nada', qa2hi:'Muy activamente',
    qa3q: '¿Fue fácil usar SpeakEase?',
    qa3lo:'Difícil', qa3hi:'Fácil',
    qa4q: '¿Fue útil WordBridge (sugerencias de palabras)?',
    qa4lo:'No útil', qa4hi:'Muy útil',
    qa5q: '¿Fueron útiles las actas en tiempo real?',
    qa5lo:'No útil', qa5hi:'Muy útil',
    qa6q: '¿Te gustaría usar este sistema de nuevo para el intercambio internacional?',
    qa6lo:'No', qa6hi:'Sí',
    wtc: [
      'Me preocupa lo que otros piensan cuando hablo inglés',
      'Me preocupa cometer errores gramaticales cuando hablo inglés',
      'Creo que sería difícil hablar inglés durante más de una hora',
      'Puedo iniciar una conversación en inglés por mi cuenta',
      'Después de una conversación, me arrepiento de no haber hablado mejor',
      'Disfruto el tiempo que paso usando el inglés',
      'Quiero estudiar más inglés en el futuro',
    ],
  },
  fr: {
    waiting:        'En attente',
    recording:      'Enregistrement',
    participants:   'Participants',
    you:            '(Vous)',
    waitingUser:    'En attente de participants...',
    times:          'fois',
    seeTranslation: 'Voir la traduction',
    close:          'Fermer',
    translating:    'Traduction...',
    transError:     'Échec de la traduction',
    transFail:      'Traduction indisponible',
    speakHint:      'Maintenez le bouton pour parler',
    listening:      'Parlez maintenant...',
    micOff:         'Micro éteint. Appuyez pour activer',
    logTitle:       'Procès-verbal en direct',
    otherCount:     'Autres participants',
    endBtn:         'Terminer',
    langLabel:      'Langue de traduction',
    wordBridge:     'Chercher des mots（WordBridge）',
    wordHint:       'Les mots apparaîtront quand vous parlerez',
    dashTitle:      'Rapport de conversation',
    dashClose:      'Fermer',
    greatJob:       'Great job! 🎉',
    dashSub:        'Bravo ! Voici votre bilan.',
    statSpeaks:     'Prises de parole',
    statWords:      'Nombre total de mots',
    statTrans:      'Traductions utilisées',
    statWB:         'WordBridge utilisé',
    statTime:       'Durée',
    statTopWords:   'Mots les plus utilisés',
    noData:         'Pas de données',
    surveyTitle:    'Questionnaire（environ 3 min）',
    surveySection1: 'À propos de la conversation d\'aujourd\'hui',
    surveySection2: 'Motivation pour l\'anglais（échelle de 6）',
    surveyWTCNote:  '1=Pas du tout d\'accord　〜　6=Tout à fait d\'accord',
    surveyFree:     'Commentaires libres',
    surveyFreePH:   'Écrivez librement ici',
    surveySubmit:   'Soumettre',
    surveyDone:     '✅ Soumis ! Merci.',
    surveyError:    'Échec de l\'envoi. Veuillez réessayer.',
    qa1q: 'Quel était votre niveau de satisfaction global aujourd\'hui ?',
    qa1lo:'Insatisfait', qa1hi:'Satisfait',
    qa2q: 'Dans quelle mesure avez-vous pu participer activement ?',
    qa2lo:'Pas du tout', qa2hi:'Très activement',
    qa3q: 'SpeakEase était-il facile à utiliser ?',
    qa3lo:'Difficile', qa3hi:'Facile',
    qa4q: 'WordBridge (suggestions de mots) était-il utile ?',
    qa4lo:'Pas utile', qa4hi:'Très utile',
    qa5q: 'Le procès-verbal en direct était-il utile ?',
    qa5lo:'Pas utile', qa5hi:'Très utile',
    qa6q: 'Souhaiteriez-vous utiliser ce système à nouveau ?',
    qa6lo:'Non', qa6hi:'Oui',
    wtc: [
      'Je me soucie de l\'opinion des autres quand je parle anglais',
      'J\'ai peur de faire des erreurs grammaticales en anglais',
      'Je pense qu\'il serait difficile de parler anglais pendant plus d\'une heure',
      'Je peux commencer une conversation en anglais de moi-même',
      'Après une conversation, je regrette de ne pas avoir mieux parlé',
      'J\'apprécie le temps que je passe à utiliser l\'anglais',
      'Je veux étudier l\'anglais davantage à l\'avenir',
    ],
  },
  de: {
    waiting:        'Warten',
    recording:      'Aufnahme',
    participants:   'Teilnehmer',
    you:            '(Sie)',
    waitingUser:    'Warten auf Teilnehmer...',
    times:          'Mal',
    seeTranslation: 'Übersetzung anzeigen',
    close:          'Schließen',
    translating:    'Übersetzen...',
    transError:     'Übersetzung fehlgeschlagen',
    transFail:      'Übersetzung nicht verfügbar',
    speakHint:      'Taste gedrückt halten zum Sprechen',
    listening:      'Bitte sprechen...',
    micOff:         'Mikrofon aus. Taste drücken zum Einschalten',
    logTitle:       'Echtzeit-Protokoll',
    otherCount:     'Andere Teilnehmer',
    endBtn:         'Beenden',
    langLabel:      'Übersetzungssprache',
    wordBridge:     'Wörter suchen（WordBridge）',
    wordHint:       'Wörter erscheinen wenn Sie sprechen',
    dashTitle:      'Gesprächsbericht',
    dashClose:      'Schließen',
    greatJob:       'Great job! 🎉',
    dashSub:        'Gut gemacht! Hier ist Ihre Aufzeichnung.',
    statSpeaks:     'Wortmeldungen',
    statWords:      'Gesamtwörter',
    statTrans:      'Übersetzungen genutzt',
    statWB:         'WordBridge genutzt',
    statTime:       'Dauer',
    statTopWords:   'Meist verwendete Wörter',
    noData:         'Keine Daten',
    surveyTitle:    'Umfrage（ca. 3 Min.）',
    surveySection1: 'Über das heutige Gespräch',
    surveySection2: 'Motivation für Englisch（6-Punkte-Skala）',
    surveyWTCNote:  '1=Stimme gar nicht zu　〜　6=Stimme voll zu',
    surveyFree:     'Freie Kommentare',
    surveyFreePH:   'Schreiben Sie hier frei',
    surveySubmit:   'Absenden',
    surveyDone:     '✅ Abgesendet! Danke.',
    surveyError:    'Fehler beim Senden. Bitte erneut versuchen.',
    qa1q: 'Wie zufrieden waren Sie insgesamt mit dem heutigen Gespräch?',
    qa1lo:'Unzufrieden', qa1hi:'Zufrieden',
    qa2q: 'Wie aktiv konnten Sie heute sprechen?',
    qa2lo:'Gar nicht', qa2hi:'Sehr aktiv',
    qa3q: 'War SpeakEase einfach zu bedienen?',
    qa3lo:'Schwierig', qa3hi:'Einfach',
    qa4q: 'War WordBridge (Wortvorschläge) hilfreich?',
    qa4lo:'Nicht hilfreich', qa4hi:'Sehr hilfreich',
    qa5q: 'War das Echtzeit-Protokoll hilfreich?',
    qa5lo:'Nicht hilfreich', qa5hi:'Sehr hilfreich',
    qa6q: 'Möchten Sie dieses System wieder für den internationalen Austausch nutzen?',
    qa6lo:'Nein', qa6hi:'Ja',
    wtc: [
      'Ich mache mir Sorgen, was andere denken, wenn ich Englisch spreche',
      'Ich mache mir Sorgen, Grammatikfehler zu machen',
      'Ich denke, es wäre schwierig, länger als eine Stunde Englisch zu sprechen',
      'Ich kann von mir aus ein Gespräch auf Englisch beginnen',
      'Nach einem Gespräch bedauere ich, nicht besser gesprochen zu haben',
      'Ich genieße die Zeit, in der ich Englisch verwende',
      'Ich möchte in Zukunft mehr Englisch lernen',
    ],
  },
  pt: {
    waiting:        'Aguardando',
    recording:      'Gravando',
    participants:   'Participantes',
    you:            '(Você)',
    waitingUser:    'Aguardando participantes...',
    times:          'vezes',
    seeTranslation: 'Ver tradução',
    close:          'Fechar',
    translating:    'Traduzindo...',
    transError:     'Falha na tradução',
    transFail:      'Não foi possível traduzir',
    speakHint:      'Segure o botão para falar',
    listening:      'Fale agora...',
    micOff:         'Microfone desligado. Pressione para ativar',
    logTitle:       'Ata em tempo real',
    otherCount:     'Outros participantes',
    endBtn:         'Encerrar',
    langLabel:      'Idioma da tradução',
    wordBridge:     'Buscar palavras（WordBridge）',
    wordHint:       'Palavras aparecerão quando você falar',
    dashTitle:      'Relatório da conversa',
    dashClose:      'Fechar',
    greatJob:       'Great job! 🎉',
    dashSub:        'Bom trabalho! Aqui está seu registro.',
    statSpeaks:     'Falas',
    statWords:      'Total de palavras',
    statTrans:      'Traduções usadas',
    statWB:         'WordBridge usado',
    statTime:       'Duração',
    statTopWords:   'Palavras mais usadas',
    noData:         'Sem dados',
    surveyTitle:    'Questionário（aprox. 3 min）',
    surveySection1: 'Sobre a conversa de hoje',
    surveySection2: 'Motivação para o inglês（escala de 6）',
    surveyWTCNote:  '1=Discordo totalmente　〜　6=Concordo totalmente',
    surveyFree:     'Comentários livres',
    surveyFreePH:   'Escreva livremente aqui',
    surveySubmit:   'Enviar respostas',
    surveyDone:     '✅ Enviado! Obrigado.',
    surveyError:    'Falha no envio. Por favor, tente novamente.',
    qa1q: 'Qual foi sua satisfação geral com a conversa de hoje?',
    qa1lo:'Insatisfeito', qa1hi:'Satisfeito',
    qa2q: 'Quão ativamente você conseguiu falar hoje?',
    qa2lo:'Nada', qa2hi:'Muito ativamente',
    qa3q: 'O SpeakEase foi fácil de usar?',
    qa3lo:'Difícil', qa3hi:'Fácil',
    qa4q: 'O WordBridge (sugestões de palavras) foi útil?',
    qa4lo:'Não útil', qa4hi:'Muito útil',
    qa5q: 'A ata em tempo real foi útil?',
    qa5lo:'Não útil', qa5hi:'Muito útil',
    qa6q: 'Você gostaria de usar este sistema novamente?',
    qa6lo:'Não', qa6hi:'Sim',
    wtc: [
      'Me preocupo com o que os outros pensam quando falo inglês',
      'Me preocupo em cometer erros gramaticais ao falar inglês',
      'Acho que seria difícil falar inglês por mais de uma hora',
      'Consigo iniciar uma conversa em inglês por conta própria',
      'Após uma conversa, me arrependo de não ter falado melhor',
      'Aproveito o tempo que passo usando o inglês',
      'Quero estudar mais inglês no futuro',
    ],
  },
};

function t(key){
  const lang = typeof myLang !== 'undefined' ? myLang : 'en';
  const texts = UI_TEXT[lang] || UI_TEXT['en'];
  return texts[key] || UI_TEXT['en'][key] || key;
}
